const message = {
    FIELD_REQUIRED: 'Trường bắt buộc',
    FIELD_UNIQUE: 'Dữ liệu đã tồn tại',
    FIELD_EXISTS: 'Đã tồn tại',
    MESSAGE_ADD_ERROR: 'Không thể thêm dữ liệu',
    MESSAGE_ADD_SUCCESSFUL: 'Thêm dữ liệu thành công',
    MESSAGE_ADD_UNIQUE: 'Mã không được trùng',
    MESSAGE_DEL_EMPTY: 'Không tìm thấy dữ liệu để xóa',
    MESSAGE_DEL_SUCCESSFUL: 'Xóa dữ liệu thành công',
    MESSAGE_DEL_ERROR: 'Xóa dữ liệu không thành công',
    MESSAGE_DEL_BLOCK: 'Không thể xóa dữ liệu đang sử dụng',
    MESSAGE_EDIT_BLOCK: 'Không thể cập nhật dữ liệu đang sử dụng',
    MESSAGE_DATA_EMPTY: 'Không tìm thấy dữ liệu',
    MESSAGE_EDIT_SUCCESSFUL: 'Cập nhật dữ liệu thành công',
    MESSAGE_EDIT_ERROR: 'Không thể cập nhật dữ liệu',
    MESSAGE_FAILED_AUTH: 'Không thể xác thực. Mời đăng nhập lại',
    MESSAGE_EXPIRED_AUTH: 'Hết phiên làm việc. Mời đăng nhập lại',
    MESSAGE_INVALID_AUTH: 'Bạn không được phép thực hiện hành động này',
    MESSAGE_SET_ROLE_SUCCESSFUL: 'Thiết lập quyền thành công',
    MESSAGE_SET_ROLE_ERROR: 'Thiết lập quyền thất bại',
    FILE_EMPTY: 'Không tìm thấy file',
    ERROR_FILE: 'Đã xảy ra lỗi. Vui lòng chọn lại file!',
    PHONE_ERR_FORMAT: 'Số điện thoại không đúng định dạng',
    EMAIL_ERR_FORMAT: 'Email không đúng định dạng',
    MESSAGE_NOT_ENOUGH_DATA: 'Chưa cập nhật đủ thông tin',
    MESSAGE_TIME_GREAT_THAN: 'Đã quá thời gian cập nhật',
    MESSAGE_STATUS_COMPLETE: 'Không thể cập nhật khi đã hoàn thành',
    MESSAGE_ERR_CONNECT: 'Không thể kết nối',
    MESSAGE_SEND_MAIL_ERR: 'Không thể gửi mail',
    MESSAGE_SEND_MAIL_SUCCESS: 'Gửi email thành công',
    MESSAGE_RESEND_CODE_SUCCESS: 'Gửi mã thành công',
    MESSAGE_RESEND_CODE_ERR: 'Gửi mã thất bại',
    MESSAGE_ACTIVE_ACCOUNT_SUCCESS: 'Kích hoạt tài khoản thành công',
    MESSAGE_ACTIVE_ACCOUNT_ERR: 'Kích hoạt tài khoản thất bại',
}

module.exports = message;
